events {}

http {
    server {
        listen 80;

        add_header Access-Control-Allow-Origin "*" always;

        location / {
            root /app/frontend;
            index index.html;
            try_files $uri /index.html =404;
        }

        location /media/ {
            alias /media/;
            autoindex on;
            autoindex_format json;
        }

        location /api/ {

            # Preflight handling
            if ($request_method = OPTIONS) {
                add_header Access-Control-Allow-Origin "*";
                add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
                add_header Access-Control-Allow-Headers "*";
                return 204;
            }

            add_header Access-Control-Allow-Origin "*" always;
            add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
            add_header Access-Control-Allow-Headers "*" always;

            proxy_pass http://127.0.0.1:7272/;
        }
    }
}